import random
import string


def generate_code(length=8):
    characters = string.ascii_lowercase + string.digits  # Include uppercase, lowercase letters, and digits
    return ''.join(random.choice(characters) for _ in range(length))


# Generate and print a 8-character alphanumeric code
code = generate_code()
print("Copy the following code into the wandb_run_id of your new config.")
print("If you do not supply a wandb_run_id, a new one will be generated by wandb, ")
print("but if you want to continue an existing run, you have to find the generated run_id ")
print("and paste it in your config, which is cumbersome.")
print("-" * 80)
print(code)
print("-" * 80)
