# usage:
# CUDA_VISIBLE_DEVICES=0 python eval_zero_shot_task.py --config-name=eval_multiple_ckpt configs.hf=["vanilla_config1","vanilla_config_2"] batch_size=64
# CUDA_VISIBLE_DEVICES=0 python eval_zero_shot_task.py --config-name=eval_multiple_ckpt configs.block=["block_config1","block_config_2"] batch_size=64

# this eval config assumes that the output_dir of the training config was null or the same as the config name
# (the part before .yaml)

name: eval_multiple_ckpt

eval_multiple_ckpt: True
ckpt_step_interval: 10000  # only evaluate ckpt with steps that are multiples of this

# whether to disable padding for evaluation
# set eval_no_pad to True when evaluating old pretrained checkpoints with >= 300M parameters.
# Block Transformers needs to be pretrained with random-length padding in the first block of each document to support
# padding. We forgot to enable this for models at or above 300M, as shown in the configs.
# Refer to `random_pad_first_block` and `pad_to_block_boundary` in the training configs.
# Note that the code is now updated to enable these by default.
eval_no_pad: False

wandb: true
wandb_entity: block-transformer
wandb_project: zero_shot_eval
wandb_run_name: null

tasks: lambada_openai,wikitext,hellaswag,piqa,arc_easy
batch_size: 64
device: cuda:0
precision: bf16

# default settings
num_fewshot: null
max_batch_size: null
limit: null
use_cache: null
decontamination_ngrams_path: null
check_integrity: False
write_out: False
log_samples: False
show_config: False
include_path: null
gen_kwargs: null
verbosity: INFO

ckpt_path: null  # abs path of the ancestor directory of the ckpts you want to evaluate. default is paths.SAVE_DIR

output_path: null
eval_last_ckpt: False  # if True, only evaluate the last ckpt for each config
min_steps: null  # select checkpoints with steps >= min_steps

configs: {
  "hf": [
#        "vanilla_31",
#        "vanilla_70",
        "vanilla_160",
#        "vanilla_410",
  ],
  "block": [
#        "block_main_b4_5",
#        "block_main_b4_19",
#        "block_main_b4_85",
        "block_main_b4_300",
#        "block_main_b4_800",
#        "block_main_b4_1.2b",
  ]
  # override these with the configs you want to evaluate
}