name: block_uptrain_b4_300_10

wandb: true
wandb_project: block_transformer
wandb_entity: block-transformer
wandb_run_name: null
output_dir: null

wandb_run_id: null
resume_from_checkpoint: false

pythia_pile_idxmaps_path: /data/pythia/pythia_pile_idxmaps
dataset: pythia_pile
block_length: 4
block_split:
  distribution: fixed
  distribution_kwargs:
    length: 4
total_batch_size: 256
per_device_train_batch_size: 8
gradient_accumulation_steps: null
batch_size_rampup_steps: null
max_length: 2048
random_pad_first_block: true
pad_to_block_boundary: true

tokenizer:
  embedder: pythia
  token_decoder: pythia

embedder:
  cls: lookup
  model_name_or_path: null
  n_embedding_tokens: 1
  use_pretrained_weights: False
  projection_method: projection_layer
  config:
    vocab_size: 50304
    hidden_size: 1024

block_decoder:
  cls: gpt-neo-x
  model_name_or_path: EleutherAI/pythia-410m-deduped
  use_pretrained_weights: False
  loss_name: null
  attn_implementation: flash_attention_2
  config:
    num_hidden_layers: 12
    hidden_size: 1024

token_decoder:
  cls: gpt-neo-x
  model_name_or_path: EleutherAI/pythia-410m-deduped
  use_pretrained_weights: False
  expansion_method: expansion_layer
  expansion_ratio: 2
  decoding_strategy: prefix
  config:
    num_hidden_layers: 12
    hidden_size: 1024

load_from_vanilla:
  enable: true
  method: partition
  initialize_mean_embedder_projection: true
  initialize_identity_expansion_layer: true
  config_path: conf/trainer/240408_poc_vanilla_410.yaml
  checkpoint_path: /root/block-transformer/results/240408_poc_vanilla_410/checkpoint-570000/model.safetensors

token_decoding_loss:
  enable: true

block_decoding_loss:
  enable: false
  weight: 1.0

auto_encoding_loss:
  enable: false
  weight: 1.0

adaptive_lr_auto_encoder: null

freeze: false
learning_rate: 3e-4
adam_beta1: 0.9
adam_beta2: 0.95
weight_decay: 0.1
precision: bf16
num_train_steps: 57200
stop_steps: 57200
num_warmup_steps: 3000
save_steps: 5000
save_total_limit: null
logging_steps: 200
dataloader_num_workers: 8

deepspeed: ds_configs/default_linear_warmup.config
